# Generated by Django 3.2.20 on 2024-04-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=200)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('shift_status', models.SmallIntegerField(choices=[(0, 'Suspend'), (1, 'Active')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
