# Generated by Django 3.2.20 on 2024-03-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlogs',
            options={'ordering': ['-systemlog_request_time']},
        ),
        migrations.AddField(
            model_name='systemlogs',
            name='systemlog_response_duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
