# Generated by Django 3.2.20 on 2024-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0002_auto_20240317_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='systemlog_request_body',
            field=models.TextField(default='-'),
        ),
    ]
