# Generated by Django 3.2.20 on 2024-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0003_alter_systemlogs_systemlog_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='systemlog_operator',
            field=models.CharField(max_length=100),
        ),
    ]
