# Generated by Django 3.2.20 on 2024-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemlogs', '0004_alter_systemlogs_systemlog_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogs',
            name='systemlog_operator_dept',
            field=models.CharField(default='IT', max_length=100),
            preserve_default=False,
        ),
    ]
