# Generated by Django 3.2.20 on 2024-05-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocking_machine_name', models.CharField(max_length=100)),
                ('clocking_machine_status', models.SmallIntegerField(choices=[('0', 'Suspend'), ('1', 'Active')], default=1)),
                ('clocking_machine_type', models.SmallIntegerField(choices=[(0, 'Finger Print'), (1, 'WebCam'), (2, 'CardTap')], default=0)),
                ('clocking_machine_firmware_version', models.CharField(default='', max_length=100)),
                ('clocking_machine_desc', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('clocking_machine_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ClockingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocking_record_datetime', models.DateTimeField()),
                ('clocking_record_is_edit', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('clocking_record_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('clocking_record_machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clocking.clockingmachine')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('manager_clocking_record_change', 'Can edit clocking record data')],
            },
        ),
        migrations.CreateModel(
            name='ClockingFingerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_record_position', models.SmallIntegerField()),
                ('finger_record_choose', models.SmallIntegerField(choices=[(0, 'Left Pinky Finger'), (1, 'Left Ring Finger'), (2, 'Left Middle Finger'), (3, 'Left Index Finger'), (4, 'Left Thumb'), (5, 'Right Pinky Finger'), (6, 'Right Ring Finger'), (7, 'Right Middle Finger'), (8, 'Right Index Finger'), (9, 'Right Thumb')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('finger_record_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('finger_record_machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clocking.clockingmachine')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
