# Generated by Django 3.2.20 on 2024-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockingmachine',
            name='clocking_machine_status',
            field=models.SmallIntegerField(choices=[(0, 'Suspend'), (1, 'Active')], default=1),
        ),
    ]
