# Generated by Django 3.2.20 on 2024-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0002_alter_clockingmachine_clocking_machine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockingfingerrecord',
            name='finger_record_machine',
        ),
        migrations.AddField(
            model_name='clockingfingerrecord',
            name='finger_record_machine',
            field=models.ManyToManyField(to='clocking.ClockingMachine'),
        ),
    ]
