# Generated by Django 3.2.20 on 2024-06-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0003_auto_20240523_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockingrecord',
            options={'ordering': ['-created_time'], 'permissions': [('manager_clocking_record_change', 'Can edit clocking record data'), ('view_timecard_personal', 'Can view timecard personal')]},
        ),
    ]
