# Generated by Django 3.2.20 on 2024-06-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0004_alter_clockingrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockingrecord',
            options={'ordering': ['-created_time'], 'permissions': [('manager_clocking_record_change', 'Can edit clocking record data'), ('view_timecard_personal', 'Can view timecard personal'), ('view_timecard_check', 'Can view timecard on calendar')]},
        ),
    ]
