# Generated by Django 3.2.20 on 2024-04-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('workshift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('schedule_work_shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshift.workshift')),
            ],
        ),
    ]
