# Generated by Django 3.2.20 on 2024-04-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshift', '0001_initial'),
        ('employee', '0004_alter_employee_options'),
        ('schedule', '0002_auto_20240422_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_plan_name', models.CharField(max_length=200)),
                ('schedule_plan_work_day', models.CharField(max_length=20)),
                ('schedule_plan_start_date', models.DateField()),
                ('schedule_plan_end_date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('schedule_plan_employee', models.ManyToManyField(to='employee.Employee')),
                ('schedule_plan_workshift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshift.workshift')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
