# Generated by Django 3.2.20 on 2024-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('schedule', '0003_scheduleplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleplan',
            name='schedule_plan_employee',
            field=models.ManyToManyField(blank=True, to='employee.Employee'),
        ),
    ]
