# Generated by Django 3.2.20 on 2024-04-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_scheduleplan_schedule_plan_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleplan',
            old_name='schedule_plan_workshift',
            new_name='schedule_plan_work_shift',
        ),
    ]
