# Generated by Django 3.2.20 on 2024-04-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_schedule_plan_workshift_scheduleplan_schedule_plan_work_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='schedule_plan_status',
            field=models.SmallIntegerField(choices=[(0, 'Suspend'), (1, 'Active')], default=1),
        ),
    ]
