# Generated by Django 3.2.20 on 2024-05-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('workshift', '0001_initial'),
        ('schedule', '0008_scheduleplan_schedule_plan_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_change_apply_reason', models.TextField(blank=True, null=True)),
                ('schedule_change_reject_reason', models.TextField(blank=True, null=True)),
                ('schedule_change_type', models.SmallIntegerField(choices=[(0, 'Short Term'), (1, 'Long Term')], default=0)),
                ('schedule_change_status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Approval'), (2, 'Reject')], default=0)),
                ('schedule_change_start_date', models.DateField(blank=True, null=True)),
                ('schedule_change_end_date', models.DateField(blank=True, null=True)),
                ('schedule_change_off_day', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_change_work_day', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('schedule_change_applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_change_applicant', to='employee.employee')),
                ('schedule_change_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_change_approver', to='employee.employee')),
                ('schedule_change_work_shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshift.workshift')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('view_schedule_change_approval', 'Can view schedule change approval list'), ('view_schedule_change_personal', 'Can view schedule change personal'), ('manager_approval_schedule_change', 'Can approval the schedule change'), ('view_schedule_change_all_report', 'Can view all schedule change report'), ('view_schedule_change_own_report', 'Can only view own schedule change report')],
            },
        ),
    ]
