# Generated by Django 3.2.20 on 2024-05-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedulechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulechange',
            old_name='schedule_change_off_day',
            new_name='schedule_change_off_date',
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='schedule_change_work_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedulechange',
            name='schedule_change_status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'Approval'), (2, 'Reject'), (3, 'Cancel')], default=0),
        ),
    ]
