# Generated by Django 3.2.20 on 2023-12-29 22:18

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('file_url', models.ImageField(blank=True, default='', null=True, upload_to=upload.models.get_today)),
                ('file_uploader', models.CharField(blank=True, max_length=20, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
