# Generated by Django 3.2.20 on 2024-02-11 22:51

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_url',
            field=models.FileField(blank=True, default='', null=True, upload_to=upload.models.get_today),
        ),
    ]
