# Generated by Django 3.2.20 on 2024-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
