# Generated by Django 3.2.20 on 2024-01-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeoffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeoff_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeoff_status', models.SmallIntegerField(choices=[(1, 'Apply'), (2, 'Manager Approval'), (3, 'HR Approval'), (4, 'Cancel')], default=1)),
                ('timeoff_start_datetime', models.DateTimeField()),
                ('timeoff_end_datetime', models.DateTimeField()),
                ('timeoff_reason', models.TextField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('timeoff_apply_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeoff_apply_employee', to='employee.employee')),
                ('timeoff_approval_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeoff_approval_employee', to='employee.employee')),
                ('timeoff_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('view_timeoff_approval', 'Can view timeoff approval list')],
            },
        ),
    ]
