# Generated by Django 3.2.20 on 2024-01-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0002_auto_20240124_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoff',
            options={'ordering': ['-created_time'], 'permissions': [('view_timeoff_approval', 'Can view timeoff approval list'), ('view_timeoff_personal', 'Can view timeoff personal'), ('manager_approval_timeoff', 'Can approval the timeoff'), ('view_timeoff_all_report', 'Can view all timeoff report'), ('view_timeoff_own_report', 'Can only view own timeoff report')]},
        ),
    ]
