# Generated by Django 3.2.20 on 2024-05-14 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('timeoff', '0004_alter_timeofftype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoff',
            options={'ordering': ['-id'], 'permissions': [('view_timeoff_personal', 'Can view timeoff personal')]},
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_apply_employee',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_approval_employee',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_end_datetime',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_reason',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_start_datetime',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_status',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_type',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='timeoff_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='timeoff_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='timeoff_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='timeoff_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimeoffApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeoff_status', models.SmallIntegerField(choices=[(1, 'Apply'), (2, 'Manager Approval'), (3, 'HR Approval'), (4, 'Cancel')], default=1)),
                ('timeoff_start_datetime', models.DateTimeField()),
                ('timeoff_end_datetime', models.DateTimeField()),
                ('timeoff_reason', models.TextField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('timeoff_applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeoff_applicant', to='employee.employee')),
                ('timeoff_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeoff_approver', to='employee.employee')),
                ('timeoff_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('view_timeoff_application_approval', 'Can view timeoff application approval list'), ('view_timeoff_application_personal', 'Can view timeoff application personal'), ('manager_approval_timeoff', 'Can approval the timeoff'), ('view_timeoff_application_all_report', 'Can view all timeoff application report'), ('view_timeoff_application_own_report', 'Can only view own timeoff application report')],
            },
        ),
    ]
