# Generated by Django 3.2.20 on 2024-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0005_auto_20240514_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_reason',
            new_name='timeoff_apply_reason',
        ),
        migrations.AddField(
            model_name='timeoffapplication',
            name='timeoff_reject_reason',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoffapplication',
            name='timeoff_status',
            field=models.SmallIntegerField(choices=[(1, 'Apply'), (2, 'Manager Approval'), (3, 'HR Approval'), (4, 'Cancel'), (5, 'Reject')], default=1),
        ),
    ]
