# Generated by Django 3.2.20 on 2024-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0006_auto_20240514_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffapplication',
            name='timeoff_reject_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
