# Generated by Django 3.2.20 on 2024-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0007_alter_timeoffapplication_timeoff_reject_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_applicant',
            new_name='timeoff_application_applicant',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_apply_reason',
            new_name='timeoff_application_apply_reason',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_approver',
            new_name='timeoff_application_approver',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_end_datetime',
            new_name='timeoff_application_end_datetime',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_reject_reason',
            new_name='timeoff_application_reject_reason',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_start_datetime',
            new_name='timeoff_application_start_datetime',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_status',
            new_name='timeoff_application_status',
        ),
        migrations.RenameField(
            model_name='timeoffapplication',
            old_name='timeoff_type',
            new_name='timeoff_application_type',
        ),
    ]
