# Generated by Django 3.2.20 on 2024-05-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0008_auto_20240514_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='timeoff_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
