# Generated by Django 3.2.20 on 2023-12-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200, unique=True)),
                ('menu_url', models.CharField(default='#', max_length=100)),
                ('menu_show', models.CharField(max_length=100)),
                ('menu_priority', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('menu_type', models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Main'), (2, 'Level1'), (3, 'Level2'), (4, 'Level3')], default=0)),
                ('menu_icon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('menu_category', models.SmallIntegerField(choices=[(0, 'Public Menu'), (1, 'IT Menu'), (2, 'HR Menu'), (3, 'Accounting Menu'), (4, 'Inventory Menu'), (5, 'Sale Menu'), (10, 'Admin Menu')], default=0)),
                ('menu_status', models.SmallIntegerField(choices=[(0, 'Suspend'), (1, 'Active')], default=1)),
                ('menu_need_id', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('menu_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menu')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.permission')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
