# Generated by Django 3.2.20 on 2024-02-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('department', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=200)),
                ('ticket_description', models.TextField()),
                ('ticket_solution', models.TextField(blank=True, null=True)),
                ('ticket_status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'On hold'), (3, 'Finished'), (4, 'Rejected'), (5, 'Closed')], default=0)),
                ('ticket_final_time', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('ticket_assign_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('ticket_assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_assigner', to='employee.employee')),
                ('ticket_attachment', models.ManyToManyField(to='upload.Upload')),
                ('ticket_creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_creator', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_time'],
                'permissions': [('view_ticket_kanban', 'Can view ticket kanban'), ('view_ticket_report', 'Can view ticket report'), ('view_ticket_personal', 'Can view ticket personal'), ('update_ticket_department', 'Can update own department tickets')],
            },
        ),
    ]
