# Generated by Django 3.2.20 on 2024-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
