# Generated by Django 3.2.20 on 2024-02-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('ticket', '0002_alter_tickettype_ticket_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.tickettype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_attachment',
            field=models.ManyToManyField(blank=True, null=True, to='upload.Upload'),
        ),
    ]
