# Generated by Django 3.2.20 on 2024-02-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20240202_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
    ]
