# Generated by Django 3.2.20 on 2024-02-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_upload_file_name'),
        ('ticket', '0006_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_attachment',
            field=models.ManyToManyField(blank=True, to='upload.Upload'),
        ),
    ]
