# Generated by Django 3.2.20 on 2024-02-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_ticket_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_time'], 'permissions': [('view_ticket_kanban', 'Can view ticket kanban'), ('view_ticket_report', 'Can view ticket report'), ('view_ticket_personal', 'Can view ticket personal'), ('view_todo_ticket_dept', 'Can view todo ticket department'), ('update_ticket_department', 'Can update own department tickets')]},
        ),
    ]
